  # Sample Actions workflow for the template
  name: Actions Template
  on:
    push:
      branches:
        - master
  jobs:
    build:
      name: Build Node
      runs-on: ubuntu-latest
      steps:
        - name: chekout brabch
          uses: actions/checkout@v2
        - name: node version
          uses: actions/setup-node@v2
          with:
            node-version: "14"
        - name: run some scripts
          run: |
            npm install
            npm run test
